const Colleges = [
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    },
    {
        college_name: "Hansraj College Delhi University - 1",
        promoted: true,
        discount: 20,
        original_fees: 6000,
        discounted_fees: 5200,
        fees_cycle: "Per Semester (3months)",
        image: "./college_01.jpg",
        ranking: "7 in 260 colleges in north campus",
        tags: ["best colleges in 2018", "2kms away"],
        amenties: ["Free cancellation", "Free Wifi"],
        rating: 4,
        rating_remarks: "Very Good",
        famous_nearest_places: "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
        nearest_place: ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
        offertext: "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
    }
]

export default Colleges;